title = "Jigsaw Puzzle"
blurb = "Calculating the number of certain pieces (row/column/border/inside/etc.) of a jigsaw puzzle"
source = "atk just started another 1000-pieces jigsaw puzzle when this idea hit him"